version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: passimx-vpn-postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    command: -p ${PG_PORT}
    expose:
      - ${PG_PORT}
    ports:
      - ${PG_PORT}:${PG_PORT}
    networks:
      - vpn-network

  app:
    image: ${DOCKER_IMAGE:-passimx/vpn-payments:latest}
    container_name: passimx-vpn-app
    restart: always
    env_file: .env
    environment:
      PG_HOST: postgres
      PG_PORT: ${PG_PORT}
      PORT: ${PORT:-2000}
    ports:
      - "${PORT:-2000}:${PORT:-2000}"
    depends_on:
      - postgres
    networks:
      - vpn-network

networks:
  vpn-network:
    driver: bridge