name: CI/CD Pipeline

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  version:
    uses: Passimx/ci-cd-workflows/.github/workflows/version.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: version
    uses: Passimx/ci-cd-workflows/.github/workflows/build.yml@main
    with:
      ORGANIZATION_NAME: ${{ vars.ORGANIZATION_NAME }}
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}
      VERSION: ${{ needs.version.outputs.release_version }}
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      GIT_HUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
    permissions:
      contents: write
      packages: write

  deploy:
    needs: build
    uses: Passimx/ci-cd-workflows/.github/workflows/deploy.yml@main
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_USER: ${{ vars.SSH_USER }}
      SSH_HOST: ${{ vars.SSH_HOST }}
      DEPLOY_SCRIPT: ${{ vars.DEPLOY_SCRIPT }}